[features]
seeds = true
skip-lint = false
[programs.localnet]
cube = "2xUjvPgGaAehA9qFz8y6U6whBeNaafkRJMeEuBoLXj9U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
